
services:
  zap-prod:
    build: .
    ports:
      - "1337:3000"
    environment:
      - ENV=production
      - PORT=3000
    restart: unless-stopped
    command: npm start
    networks:
     - proxy-network

  zap-dev:
    build: .
    ports:
      - "1338:3000"
    environment:
      - ENV=dev
      - PORT=3000
    volumes:
      - ./app:/app/app
      - ./server.js:/app/server.js
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
    networks:
     - proxy-network

networks:
  proxy-network:
    external: true
