#!/usr/bin/env node

/**
 * Publish script for BubbleZap 3D
 * Updates version across all files
 * Usage: npm run publish <version>
 * Example: npm run publish 1.2.0
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

// Get version from command line
const version = process.argv[2];

if (!version) {
    console.error('❌ Error: Version string required');
    console.log('Usage: npm run publish <version>');
    console.log('Example: npm run publish 1.2.0');
    process.exit(1);
}

// Validate semver format (basic check)
if (!/^\d+\.\d+\.\d+(-[a-zA-Z0-9.]+)?$/.test(version)) {
    console.error('❌ Error: Invalid semver format');
    console.log('Expected format: X.Y.Z or X.Y.Z-tag');
    console.log('Example: 1.2.0 or 1.2.0-beta.1');
    process.exit(1);
}

console.log(`\n🚀 Publishing BubbleZap 3D v${version}\n`);

// 1. Update package.json
console.log('📦 Updating package.json...');
const packagePath = path.join(rootDir, 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
packageJson.version = version;
fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2) + '\n');
console.log('✅ package.json updated');

// 2. Update service worker cache version
console.log('🔄 Updating service worker cache...');
const swPath = path.join(rootDir, 'app', 'js', 'sw.js');
let swContent = fs.readFileSync(swPath, 'utf8');
swContent = swContent.replace(
    /const CACHE_VERSION = ['"]bubble-zap-v[^'"]+['"]/,
    `const CACHE_VERSION = 'bubble-zap-v${version}'`
);
fs.writeFileSync(swPath, swContent);
console.log('✅ Service worker cache updated');

// 3. Update manifest.json version
console.log('📱 Updating manifest.json...');
const manifestPath = path.join(rootDir, 'app', 'assets', 'manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
manifest.version = version;
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
console.log('✅ manifest.json updated');

// 4. Create version.js file for runtime access
console.log('🏷️  Creating version.js...');
const versionJs = `// Auto-generated by publish.js
window.BUBBLEZAP_VERSION = '${version}';
`;
const versionPath = path.join(rootDir, 'app', 'js', 'version.js');
fs.writeFileSync(versionPath, versionJs);
console.log('✅ version.js created');

console.log(`\n✅ Successfully published v${version}!`);
console.log('\nNext steps:');
console.log('1. Test the game to ensure everything works');
console.log('2. Commit changes: git add . && git commit -m "Release v' + version + '"');
console.log('3. Create tag: git tag v' + version);
console.log('4. Push: git push && git push --tags');
console.log();
